### ISSUE TITLE
Cannot run docker-compose: docker images are hosted on Google Cloud, which I don't have access to

### ISSUE THREAD

**Issue by micheltank** [speedscale/speedscale-cli#6]
When running: docker-compose --file docker-proxy-capture.yaml --env-file config.env up -d
I got:
ERROR: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

These images should be in a public image registry.

**Comment by swtch1** [comment]
Thank you Michel.  We discussed this in the [Speedscale Community Slack](https://speedscalecommunity.slack.com/archives/C02GUR2UWS1/p1648130325940659), but I will respond here for completeness.

To be clear this is referencing our internal CLI tool `speedctl` which has yet to merge with the speedscale-cli here.  

This is a bug where we initialize your Speedscale config.yaml file with `container-registry: gcr.io/speedscale`.  The fix is to change this line to `container-registry: public.ecr.aws/speedscale` and re-generate the docker-compose file.  We will correct the registry setting in an upcoming release.
